### ISSUE TITLE
Different result from two runs of MFEprimer with same condition

### ISSUE THREAD

**Issue by linglilongyi** [quwubin/MFEprimer-3.0#14]
With the same input primer fasta and the same indexed database, MFEprimer gives different output in different run.
The amplicons and the pair of primers could change for some reason.
Is there some bugs to be fixed?

`diff output/test1.txt output/test.txt`
 >312c312
>Amp_11 primer1 + primer2 ==> chr:986768-988086 
>Amp_11 primer1 + primer3 ==> chr:986768-988086 

or

Amp_11 shows in the first run output but not in the second one.

**Comment by quwubin** [comment]
There is a step to randomly remove duplication amplicons, which defined by the same start and the same end position. 

It seems that this is a bug, and I will fix it next release.

**Comment by quwubin** [comment]
fixed and please test the latest version: https://github.com/quwubin/MFEprimer-3.0/releases/tag/v3.2.6.

**Comment by linglilongyi** [comment]
thank you very much！

**Comment by linglilongyi** [comment]
> fixed and please test the latest version: https://github.com/quwubin/MFEprimer-3.0/releases/tag/v3.2.6.

I've tried some runs with the latest version, but I am afraid that the proplem is not solved yet.
The detail values in each item of the same amplicon are the same, but outputs come with different amount of amlicon and different specific amplicon.

Hope the very brief description could help you located the bug.
My database some assemblies of one species.
```
[input]mfeprimer-3.2.6 -i /primer.fa -d db.fa -c 30  -j -o repeat1_amplicon.txt
[input]]mfeprimer-3.2.6 -i /primer.fa -d db.fa -c 30  -j -o repeat2_amplicon.txt
[input]wc -l repeat1_amplicon.txt repeat2_amplicon.txt
[output]2419992 repeat1_amplicon.txt
[output]2420115 repeat2_amplicon.txt
[output]4840107 total
```
And I also find different amout of amplicons with each specific pair of primers.


Thanks for your atribution to this helpful software again!

**Comment by quwubin** [comment]
Can you help me screenshot some different amplicons? I need more information.

**Comment by linglilongyi** [comment]
> 

![1652337209(1)](https://user-images.githubusercontent.com/46670292/168006704-e5d98712-4bac-44fb-887e-66b0dfe031a6.png)

The amplicon in this screenshot is shown after the first run but not in the second.
The amplicons that are showed both in two runs share same infomation include dG, Tm and so on. The point is the AMOUNT or whether an amplicon is FILTERED or REMOVED in the same rule.


![image](https://user-images.githubusercontent.com/46670292/168008110-43edf772-840a-4567-bcf0-23d2a5b89e86.png)
Another example is here.(sorry for cover some infomation).
In the example the two different reverse primer share same sequence, and the primer set shows in left or right (first and second repeat) doesn't shows in the opposite. I think it is not that import but I shows it as well.


Sincerely
LZQ
